services:
  lenslocked-db:
    image: postgres:latest
    container_name: lenslocked-db
    environment:
      POSTGRES_PASSWORD: iampassword
      POSTGRES_USER: postgres
      POSTGRES_DB: lenslocked
    ports:
      - "5464:5432"
    volumes:
      - pgdata-lenslocked:/var/lib/postgresql/data  # Persist data using a Docker volume
    restart: always  # Optional: Automatically restart the container if it fails or is stopped

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports: 
      - 3000:8080

volumes:
  pgdata-lenslocked:  # Define a volume named 'pgdata' for persistent storage
